
with get_raw_data as (
SELECT
    EmpID AS emp_id,
    Age AS age,
    AgeGroup AS age_group,
    Attrition AS attrition,
    BusinessTravel AS business_travel,
    DailyRate AS daily_rate,
    Department AS department,
    DistanceFromHome AS distance_from_home,
    Education AS education,
    EducationField AS education_field,
    EmployeeCount AS employee_count,
    EmployeeNumber AS employee_number,
    EnvironmentSatisfaction AS environment_satisfaction,
    Gender AS gender,
    HourlyRate AS hourly_rate,
    JobInvolvement AS job_involvement,
    JobLevel AS job_level,
    JobRole AS job_role,
    JobSatisfaction AS job_satisfaction,
    MaritalStatus AS marital_status,
    MonthlyIncome AS monthly_income,
    SalarySlab AS salary_slab,
    MonthlyRate AS monthly_rate,
    NumCompaniesWorked AS num_companies_worked,
    Over18 AS over_18,
    OverTime AS over_time,
    PercentSalaryHike AS percent_salary_hike,
    PerformanceRating AS performance_rating,
    RelationshipSatisfaction AS relationship_satisfaction,
    StandardHours AS standard_hours,
    StockOptionLevel AS stock_option_level,
    TotalWorkingYears AS total_working_years,
    TrainingTimesLastYear AS training_times_last_year,
    WorkLifeBalance AS work_life_balance,
    YearsAtCompany AS years_at_company,
    YearsInCurrentRole AS years_in_current_role,
    YearsSinceLastPromotion AS years_since_last_promotion,
    YearsWithCurrManager AS years_with_curr_manager

FROM {{ source('staging', 'hr_data') }} )
select * from get_raw_data